language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project coursetracker-in — token "1/3-KseGEy-F_EdAAb_ZZLIeeEk76svjMZAwIw8J_L294"
